[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.2.1"
authors = ["Trim21 <trim21.me@gmail.com>"]
edition = "2024"
homepage = "https://github.com/trim21/beancount-format"
license = "MIT"
repository = "https://github.com/trim21/beancount-format"
description = "Beancount formatter library and tooling."

[workspace.dependencies]
anyhow = "1.0.104"
beancount-formatter = { path = "./crates/beancount-formatter/" }
beancount-parser = { git = "https://github.com/trim21/beancount.git", rev = "079bd1db77e09ad030329c6ec30744ed42a938d3" }
serde = { version = "1.0.229", features = ["derive"] }

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"
