version: 3

tasks:
  default:
    - black .
    - ruff check . --fix

  minor:
    cmds:
      - pyproject-bump minor
      - task: bump

  patch:
    cmds:
      - pyproject-bump micro
      - task: bump

  bump:
    vars:
      VERSION:
        sh: yq '.project.version' pyproject.toml
    cmds:
      - git add pyproject.toml
      - 'git commit -m "bump: {{.VERSION}}"'
      - 'git tag "v{{.VERSION}}" -m "v{{.VERSION}}"'
