version: "3"

tasks:
  default:
    - task: fmt
    - task: lint
    - task: test

  build:wasm:
    desc: Build the dprint beancount plugin wasm artifact
    env:
      RUSTFLAGS: "-C link-args=--max-memory=4294967296 -C link-arg=--initial-heap=104857600"
    cmds:
      - cargo build -p dprint-plugin-beancount --target wasm32-unknown-unknown --features wasm --release
      - cp ./target/wasm32-unknown-unknown/release/dprint_plugin_beancount.wasm ./plugin.wasm

  build:cli:
    desc: Build the CLI binary
    cmds:
      - cargo build -p beancount-formatter-cli --release

  build:pypi:
    desc: Build the PyPI package via maturin (python feature)
    cmds:
      - maturin build --release

  test:
    desc: Run Rust tests
    cmds:
      - cargo test --workspace

  test:cli:
    desc: Run CLI end-to-end tests
    cmds:
      - cargo test -p beancount-formatter-cli --test cli_e2e

  lint:
    desc: Run clippy lints
    cmds:
      - cargo clippy --workspace --all-targets --all-features -- -D warnings

  lint:fix:
    desc: Run clippy lints
    cmds:
      - cargo clippy --allow-dirty --fix --workspace --all-targets --all-features -- -D warnings

  fmt:
    desc: Run Rust formatter
    cmds:
      - cargo fmt --all

  bump:
    vars:
      VERSION:
        sh: yq '.workspace.package.version' Cargo.toml
    cmds:
      - python scripts/update_versions.py
      - cargo generate-lockfile
      - git add pyproject.toml package.json Cargo.toml Cargo.lock
      - 'git commit -m "bump: {{.VERSION}}"'
      - 'git tag "v{{.VERSION}}" -m "v{{.VERSION}}"'
